/* =====================================================================
   game.js -- THE RULES AND THE LOOP.
   ===================================================================== */
var Game = { mode: "choice", levelNumber: 0, nextEnemy: null, goldTesseracts: 0, curses: [], blessings: { jump: 0, ammo: 0, speed: 0, dash: 0, magnet: 0 } };
Game.hasCurse = function (id) { return Game.curses.indexOf(id) >= 0; };
Game.curseCount = function (id) { return Game.curses.filter(function (curse) { return curse === id; }).length; };
Game.curseChoices = [
   { id: "roughEdging", name: "Rough Edging", description: "Movement acceleration is 10% slower." },
   { id: "unknownDimension", name: "Unknown Dimension", description: "Cuboids can combine again." },
   { id: "batteryLife", name: "Battery Life", description: "Drills get a second dash." },
   { id: "lowerGravity", name: "Lower Gravity", description: "You'd think this would be helpful." },
   { id: "unstablePlain", name: "Unstable Plain", description: "Diamon tesseracts are worth double, but the map collapses around you in fast, short bursts." },
   { id: "shotgunSlug", name: "Shotgun Slug", description: "Drones fire one faster, focused shot instead of a burst." },
   { id: "fiveCube", name: "5-Cube", description: "Orange fake tesseracts are lethal. Do not touch them." },
   { id: "wearAndTear", name: "Wear and Tear", description: "Your weapon damage is reduced by 25%." }
];
Game.startRound = function () { Game.showClassChoice(); };
Game.startLevel = function (levelNumber, enemyType) { var resetRoster = levelNumber === CONFIG.START_LEVEL && !enemyType; Game.levelNumber = levelNumber; Level.build(levelNumber); Player.reset(); Weapons.reset(); Enemy.reset(enemyType, resetRoster); Game.mode = "playing"; Game.showMessage("Level " + (levelNumber + 1) + " - " + Player.classType); };
Game.showClassChoice = function () { Game.mode = "choice"; Game.goldTesseracts = 0; Game.curses = []; Game.blessings = { jump: 0, ammo: 0, speed: 0, dash: 0, magnet: 0 }; Game.blessingOffers = null; var panel = document.getElementById("class-choice"), cards = document.getElementById("class-cards"); cards.innerHTML = ""; [{ type: "bazooka", name: "Bazooka", description: "85 DMG, 6 ammo, 4s reload. Explosive shots destroy terrain." }, { type: "tomahawk", name: "Tomahawk", description: "10 DMG throwing axes, automatic, 0.7s cooldown. E hurls a 3-axe volley." }, { type: "pistols", name: "Pistols", description: "4 DMG, 24 ammo, 3s reload. E dashes toward the mouse and grants immunity." }, { type: "katana", name: "Katana", description: "8 DMG melee slash every 0.6s. E parries attacks." }].forEach(function (choice) { var button = document.createElement("button"); button.className = "class-card"; button.innerHTML = "<strong>" + choice.name + "</strong><span>" + choice.description + "</span>"; button.addEventListener("click", function () { panel.hidden = true; Player.classType = choice.type; Game.showCurseChoice(CONFIG.START_LEVEL); }); cards.appendChild(button); }); panel.hidden = false; Game.showMessage("Choose your class"); };
Game.nextLevel = function () { Game.showBlessingChoice(Game.levelNumber + 1); };
Game.blessingDefinitions = [{ type: "jump", name: "High Jump", description: "+2 jump power", cost: CONFIG.BLESSING_COSTS.jump }, { type: "ammo", name: "Deep Pockets", description: "+2 ammo per reload", cost: CONFIG.BLESSING_COSTS.ammo }, { type: "speed", name: "Quick Roll", description: "+0.05 movement acceleration", cost: CONFIG.BLESSING_COSTS.speed }, { type: "dash", name: "Long Dash", description: "+6 dash frames", cost: CONFIG.BLESSING_COSTS.dash }, { type: "magnet", name: "Tesseract Pull", description: "+20 collection range", cost: CONFIG.BLESSING_COSTS.magnet }];
Game.nextBlessingOffer = function () { return Game.blessingDefinitions[Math.floor(Math.random() * Game.blessingDefinitions.length)]; };
Game.ensureBlessingOffers = function () { if (!Game.blessingOffers) Game.blessingOffers = [Game.nextBlessingOffer(), Game.nextBlessingOffer()]; };
Game.showCurseChoice = function (nextLevel) { Game.mode = "choice"; var panel = document.getElementById("curse-choice"), cards = document.getElementById("curse-cards"); cards.innerHTML = ""; var pool = Game.curseChoices.slice(), choices = []; while (choices.length < 3) choices.push(pool.splice(Math.floor(Math.random() * pool.length), 1)[0]); Game.showMessage("Choose a curse for level " + (nextLevel + 1)); choices.forEach(function (choice) { var button = document.createElement("button"); button.className = "curse-card"; button.innerHTML = "<strong>" + choice.name + "</strong><span>" + choice.description + "</span>"; button.addEventListener("click", function () { Game.curses.push(choice.id); panel.hidden = true; if (nextLevel === CONFIG.START_LEVEL) Game.startLevel(nextLevel); else Game.showEnemyChoice(nextLevel); }); cards.appendChild(button); }); panel.hidden = false; };
Game.showBlessingChoice = function (nextLevel) { Game.mode = "choice"; Game.ensureBlessingOffers(); var panel = document.getElementById("blessing-choice"), cards = document.getElementById("blessing-cards"); cards.innerHTML = ""; document.getElementById("blessing-gold").textContent = Game.goldTesseracts; Game.showMessage("Spend gold tesseracts before level " + (nextLevel + 1)); Game.blessingOffers.forEach(function (choice, offerIndex) { var button = document.createElement("button"); button.className = "blessing-card"; button.disabled = Game.goldTesseracts < choice.cost; button.innerHTML = "<strong>" + choice.name + "</strong><span>" + choice.description + "</span><span>Cost: " + choice.cost + " gold</span><span>Owned: " + Game.blessings[choice.type] + "</span>"; button.addEventListener("click", function () { if (Game.goldTesseracts < choice.cost) return; Game.goldTesseracts -= choice.cost; Game.blessings[choice.type]++; Game.blessingOffers[offerIndex] = Game.nextBlessingOffer(); Game.showBlessingChoice(nextLevel); }); cards.appendChild(button); }); var continueButton = document.createElement("button"); continueButton.className = "continue-button"; continueButton.textContent = "Continue"; continueButton.addEventListener("click", function () { panel.hidden = true; Game.showCurseChoice(nextLevel); }); cards.appendChild(continueButton); panel.hidden = false; };
Game.showEnemyChoice = function (nextLevel) { Game.mode = "choice"; var panel = document.getElementById("enemy-choice"), cards = document.getElementById("enemy-cards"); cards.innerHTML = ""; Game.showMessage("Choose an enemy for level " + (nextLevel + 1)); Enemy.randomChoices().forEach(function (choice) { var button = document.createElement("button"); button.className = "enemy-card"; button.innerHTML = "<strong>" + choice.name + "</strong><span>" + choice.description + "</span>"; button.addEventListener("click", function () { panel.hidden = true; Game.startLevel(nextLevel, choice.type); }); cards.appendChild(button); }); panel.hidden = false; };
Game.showMessage = function (text) { document.getElementById("message").textContent = text; };
Game.update = function () { if (Input.restart) { document.getElementById("enemy-choice").hidden = true; document.getElementById("blessing-choice").hidden = true; document.getElementById("curse-choice").hidden = true; Game.showClassChoice(); return; } if (Game.mode !== "playing") return; Player.update(); Level.updateTesseracts(); Level.updateCollapse(); Level.finishCollapse(); Enemy.update(); if (Player.isDead() || Enemy.hitsPlayer()) { Game.levelNumber = CONFIG.START_LEVEL; Game.mode = "dead"; Game.showMessage("You hit something. Press R to return to class select."); return; } if (Player.hasWon()) Game.nextLevel(); };
Game.loop = function () { Game.update(); Draw.updateCamera(); Draw.everything(); window.requestAnimationFrame(Game.loop); };